apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartmanufacturing-gitops-fashion-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smartmanufacturing-gitops-fashion-app
  template:
    metadata:
      labels:
        app: smartmanufacturing-gitops-fashion-app
    spec:
      containers:
        - name: smartmanufacturing-gitops-fashion-app
          image: priyank179/gitops_project:latest
          ports:
            - containerPort: 5000 # Kubernetes port exposed