apiVersion: v1
kind: Service
metadata:
  name: smartmanufacturing-app-service
spec:
  selector:
    app: smartmanufacturing-gitops-fashion-app

  ports:
    - port: 80 # service port 
      targetPort: 5000 # application port the current service is servicing
  type: NodePort