apiVersion: v1
kind: Service
metadata:
  name: my_manufacturing_app_service
spec:
  selector:
    app: SmartManuFacturing_MLOpsFashion_app

  ports:
    - port: 80 # service port 
      targetPort: 5000 # application port the current service is servicing
  type: NodePort